# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-03 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import miniproject.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(blank=True, default=miniproject.models.get_utc_epoch_time)),
                ('name', models.CharField(max_length=100)),
                ('file_url', models.CharField(max_length=100)),
                ('tags', django_mysql.models.JSONField(default=dict)),
                ('program', models.CharField(choices=[(b'ELAA', b'ELAA'), (b'GED', b'GED')], default=b'ELAA', max_length=255)),
                ('subject', django_mysql.models.JSONField(default=dict)),
                ('level', django_mysql.models.JSONField(default=dict)),
                ('block', models.IntegerField()),
                ('standard', models.IntegerField()),
            ],
            options={
                'db_table': 'lesson',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('username', models.CharField(max_length=15, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('reset_link', models.CharField(default=None, max_length=255, null=True)),
                ('reset_date', models.IntegerField(blank=True, default=None, null=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='miniproject.User'),
        ),
    ]
